// let userData;
const userData = [
  {
    name: 'firstName lastName',
    email: 'email@email.com',
    username: 'userName',
    provider: 'local',
    avatar: 1,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'second user',
    email: 'email2@email.com',
    username: 'userName2',
    provider: 'local',
    avatar: 3,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'third user',
    email: 'email3@email.com',
    username: 'userName3',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'fourth user',
    email: 'email4@email.com',
    username: 'userName4',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'fifth user',
    email: 'email5@email.com',
    username: 'userName5',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'sixth user',
    email: 'email6@email.com',
    username: 'userName6',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'seventh user',
    email: 'email7@email.com',
    username: 'userName7',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'eigth user',
    email: 'email8@email.com',
    username: 'userName8',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'ninth user',
    email: 'email9@email.com',
    username: 'userName9',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'tenth user',
    email: 'email10@email.com',
    username: 'userName10',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'eleventh user',
    email: 'email11@email.com',
    username: 'userName11',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'twelfth user',
    email: 'email12@email.com',
    username: 'userName12',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'thirteenth user',
    email: 'email13@email.com',
    username: 'userName13',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'fourteenth user',
    email: 'email14@email.com',
    username: 'userName14',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  },
  {
    name: 'fifteenth user',
    email: 'email5@email.com',
    username: 'userName15',
    provider: 'local',
    avatar: 2,
    premium: 0,
    donations: [],
    facebook: {},
    twitter: {},
    github: {},
    google: {}
  }
];

export default userData;
